services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tamborete
      POSTGRES_PASSWORD: tamborete
      POSTGRES_DB: capture_split
    ports:
      - "5432:5432"

  dynamodb:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    ports:
      - "8000:8000"
